### ISSUE TITLE
Signature does not belong to issuer

### ISSUE THREAD

**Issue by xunorus** [ceramicstudio/tutorial-getting-started-with-ceramic#4]
Im login with brave wallet, any ideas how is this happening?
```
main.js:74 Error: HTTP request to 'https://ceramic-clay.3boxlabs.com/api/v0/commits' failed with status '': {"error":"Can not verify signature for commit bagcqceraarbqg2iwjqnt6weuowmjfexoruwcuznrky6qgy7oxbc6bradnyrq: Signature does not belong to issuer"}
    at fetchJson (http-utils.js:25:15)
    at async Document.applyCommit (document.js:66:27)
    at async CeramicClient.applyCommit (ceramic-http-client.js:118:26)
    at async TileDocument.update (tile-document.js:130:25)
    at async DIDDataStore._getOwnIDXDoc (index.js:285:13)
    at async TileProxy.eval (index.js:296:84)
    at async TileProxy.get (proxy.js:84:67)
    at async DIDDataStore.getIndex (index.js:232:65)
    at async DIDDataStore.getRecordID (index.js:324:23)
    at async DIDDataStore.getRecordDocument (index.js:330:20)
```

**Comment by marsrobertson** [comment]
### Same here.

1. Clone repo.
2. `npm install`
3. `python3 -m http.server`
4. `http://localhost:8000`

<img width="687" alt="image" src="https://user-images.githubusercontent.com/44369284/227519630-04995e2b-a94e-4c8a-9ad7-32428a4a41e4.png">
